#!/usr/bin/env python3
import os
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir))

from together.together import Together

if len(sys.argv) is not 2:
  print('Usage: generate <inputfile.csv>')
else:
  Together(sys.argv[1]).run()
